// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWBtulEGxGyiLvFqrtanLb4Cz2Jq1tKw',
    appId: '1:990838959923:web:12ace8429638fd5c121846',
    messagingSenderId: '990838959923',
    projectId: 'progetto-pizzeria-43019',
    authDomain: 'progetto-pizzeria-43019.firebaseapp.com',
    storageBucket: 'progetto-pizzeria-43019.appspot.com',
    measurementId: 'G-21L5PRBKWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFe3geU0K0z_ckSLiSRasioLlWuNdk3vw',
    appId: '1:990838959923:android:95bc486b65d7484a121846',
    messagingSenderId: '990838959923',
    projectId: 'progetto-pizzeria-43019',
    storageBucket: 'progetto-pizzeria-43019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrE-yHLBUuHmkdJuQVRtL_Q-045OWiiZw',
    appId: '1:990838959923:ios:eee66318fae130f7121846',
    messagingSenderId: '990838959923',
    projectId: 'progetto-pizzeria-43019',
    storageBucket: 'progetto-pizzeria-43019.appspot.com',
    iosClientId: '990838959923-ufav6sbbhnbbto5l62epc3gb0mqqg3k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rioGym',
  );
}
